[tool.poetry]
name = "easy-mod"
version = "1.2.0"
description = ""
authors = ["Paweł Kucmus <pkucmus@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
mkdocs-material = "^7.2.6"
mkdocs-minify-plugin = "^0.3.0"
mkdocs-redirects = "^1.0.1"
mkdocs-macros-plugin = "^0.5.0"
mkdocs-awesome-pages-plugin = "^2.5.0"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
readline = "^6.2.4"
eva-3d = {path = "eva-docs-builder", develop = true}
ipdb = "^0.13.4"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
